#!/usr/bin/env python3
"""Agent 2: Review pull requests using Claude CLI (translated from critic.ps1).

Generates a diff for the PR, sends it to Claude for code review,
then posts an approval or change-request review via gh CLI.
"""

import json
import subprocess
import sys

from claude_cli import invoke_claude_cli
from agent_loader import get_agent_content
from config_loader import get_agent_config
from logger import get_logger
from prompt_loader import get_prompt_template

log = get_logger("critic")


def run_git(*args) -> subprocess.CompletedProcess:
    return subprocess.run(["git"] + list(args), capture_output=True, text=True, encoding="utf-8")


def run_gh(*args) -> subprocess.CompletedProcess:
    return subprocess.run(["gh"] + list(args), capture_output=True, text=True, encoding="utf-8")


def main(pr_number: int) -> int:
    """Review a pull request.

    Args:
        pr_number: The pull request number to review.

    Returns:
        Exit code (0 for success, 1 for failure).
    """
    # --- Check if PR is still open ---
    result = run_gh("pr", "view", str(pr_number), "--json", "state")
    try:
        state = json.loads(result.stdout).get("state", "")
    except (json.JSONDecodeError, ValueError):
        state = ""
    if state != "OPEN":
        log.info("PR #%d is %s. Skipping review.", pr_number, state or "unknown")
        return 0

    # --- Configuration ---
    cfg = get_agent_config("critic")
    stack = cfg["stack"]
    criteria_list = cfg["criteria_list"]
    max_diff_kb = cfg["max_diff_kb"]

    # --- Load agent content ---
    agent_content = get_agent_content(
        "critic",
        max_file_chars=cfg["agent_max_file_kb"] * 1024,
        max_total_chars=cfg["agent_max_total_kb"] * 1024,
    )

    # --- Generate diff ---
    log.info("=== CRITIC START === Reviewing PR #%d", pr_number)
    log.info("Generating diff for PR #%d...", pr_number)
    result = run_git("diff", "origin/main...HEAD")
    if result.returncode != 0:
        log.error("Failed to generate diff: %s", result.stderr or result.stdout)
        return 1

    diff_string = result.stdout
    if not diff_string or not diff_string.strip():
        log.info("No changes found in diff. Skipping review.")
        return 0

    # Truncate if too large
    max_diff_bytes = max_diff_kb * 1024
    if len(diff_string) > max_diff_bytes:
        log.warning("Diff exceeds %dKB, truncating...", max_diff_kb)
        diff_string = diff_string[:max_diff_bytes]
        diff_string += f"\n\n... [diff truncated at {max_diff_kb}KB] ..."

    # --- Build prompt ---
    prompt = get_prompt_template(
        agent_name="critic",
        tokens={
            "STACK": stack,
            "CRITERIA_LIST": criteria_list,
            "DIFF_STRING": diff_string,
        },
        agent_content=agent_content,
    )

    # --- Invoke Claude ---
    log.info("Invoking Claude CLI to review PR #%d...", pr_number)
    claude_result = invoke_claude_cli(prompt)

    review_output = claude_result["output"]
    log.debug("Claude review output:\n%s", review_output)

    if claude_result["exit_code"] != 0:
        log.warning("Claude CLI exited with code %d. Skipping review to avoid blocking PR.", claude_result["exit_code"])
        return 0

    review_text = review_output if review_output else ""

    # --- Post review ---
    review_body = f"{review_text}\n\n---\nGenerated by claude-agent-swarm (critic)"

    if review_text.lstrip().startswith("LGTM"):
        review_result = "APPROVED"
        log.info("Review result: %s", review_result)
        result = run_gh("pr", "review", str(pr_number), "--approve", "--body", review_body)
        if result.returncode != 0:
            log.warning("Failed to post approval review: %s", result.stderr or result.stdout)
    else:
        review_result = "CHANGES REQUESTED"
        log.info("Review result: %s", review_result)
        result = run_gh("pr", "review", str(pr_number), "--request-changes", "--body", review_body)
        if result.returncode != 0:
            log.warning("Failed to post change-request review: %s", result.stderr or result.stdout)

    log.info("=== CRITIC COMPLETE === PR #%d - Result: %s", pr_number, review_result)
    return 0


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Critic agent")
    parser.add_argument("pr_number", type=int)
    args = parser.parse_args()
    sys.exit(main(args.pr_number))
